//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.29 at 09:11:55 PM EEST 
//


package com.training.quizzer.soap;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.training.quizzer.soap package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.training.quizzer.soap
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RemoveWarehousesFromLocationResponse }
     * 
     */
    public RemoveWarehousesFromLocationResponse createRemoveWarehousesFromLocationResponse() {
        return new RemoveWarehousesFromLocationResponse();
    }

    /**
     * Create an instance of {@link FindAllLocationsRequest }
     * 
     */
    public FindAllLocationsRequest createFindAllLocationsRequest() {
        return new FindAllLocationsRequest();
    }

    /**
     * Create an instance of {@link FindAllProductsRequest }
     * 
     */
    public FindAllProductsRequest createFindAllProductsRequest() {
        return new FindAllProductsRequest();
    }

    /**
     * Create an instance of {@link ChangeWarehouseLocationResponse }
     * 
     */
    public ChangeWarehouseLocationResponse createChangeWarehouseLocationResponse() {
        return new ChangeWarehouseLocationResponse();
    }

    /**
     * Create an instance of {@link CreateLocationRequest }
     * 
     */
    public CreateLocationRequest createCreateLocationRequest() {
        return new CreateLocationRequest();
    }

    /**
     * Create an instance of {@link FindProductByIdRequest }
     * 
     */
    public FindProductByIdRequest createFindProductByIdRequest() {
        return new FindProductByIdRequest();
    }

    /**
     * Create an instance of {@link ChangeWarehouseLocationRequest }
     * 
     */
    public ChangeWarehouseLocationRequest createChangeWarehouseLocationRequest() {
        return new ChangeWarehouseLocationRequest();
    }

    /**
     * Create an instance of {@link FindProductsFromWarehouseRequest }
     * 
     */
    public FindProductsFromWarehouseRequest createFindProductsFromWarehouseRequest() {
        return new FindProductsFromWarehouseRequest();
    }

    /**
     * Create an instance of {@link DeleteLocationResponse }
     * 
     */
    public DeleteLocationResponse createDeleteLocationResponse() {
        return new DeleteLocationResponse();
    }

    /**
     * Create an instance of {@link FindAllWarehousesRequest }
     * 
     */
    public FindAllWarehousesRequest createFindAllWarehousesRequest() {
        return new FindAllWarehousesRequest();
    }

    /**
     * Create an instance of {@link FindWarehouseByNameRequest }
     * 
     */
    public FindWarehouseByNameRequest createFindWarehouseByNameRequest() {
        return new FindWarehouseByNameRequest();
    }

    /**
     * Create an instance of {@link RenameWarehouseResponse }
     * 
     */
    public RenameWarehouseResponse createRenameWarehouseResponse() {
        return new RenameWarehouseResponse();
    }

    /**
     * Create an instance of {@link FindLocationByNameRequest }
     * 
     */
    public FindLocationByNameRequest createFindLocationByNameRequest() {
        return new FindLocationByNameRequest();
    }

    /**
     * Create an instance of {@link CreateProductRequest }
     * 
     */
    public CreateProductRequest createCreateProductRequest() {
        return new CreateProductRequest();
    }

    /**
     * Create an instance of {@link FindWarehousesFromLocationResponse }
     * 
     */
    public FindWarehousesFromLocationResponse createFindWarehousesFromLocationResponse() {
        return new FindWarehousesFromLocationResponse();
    }

    /**
     * Create an instance of {@link Warehouse }
     * 
     */
    public Warehouse createWarehouse() {
        return new Warehouse();
    }

    /**
     * Create an instance of {@link CreateWarehouseRequest }
     * 
     */
    public CreateWarehouseRequest createCreateWarehouseRequest() {
        return new CreateWarehouseRequest();
    }

    /**
     * Create an instance of {@link FindLocationByIdRequest }
     * 
     */
    public FindLocationByIdRequest createFindLocationByIdRequest() {
        return new FindLocationByIdRequest();
    }

    /**
     * Create an instance of {@link DeleteLocationRequest }
     * 
     */
    public DeleteLocationRequest createDeleteLocationRequest() {
        return new DeleteLocationRequest();
    }

    /**
     * Create an instance of {@link CreateLocationResponse }
     * 
     */
    public CreateLocationResponse createCreateLocationResponse() {
        return new CreateLocationResponse();
    }

    /**
     * Create an instance of {@link RenameWarehouseRequest }
     * 
     */
    public RenameWarehouseRequest createRenameWarehouseRequest() {
        return new RenameWarehouseRequest();
    }

    /**
     * Create an instance of {@link DeleteWarehouseResponse }
     * 
     */
    public DeleteWarehouseResponse createDeleteWarehouseResponse() {
        return new DeleteWarehouseResponse();
    }

    /**
     * Create an instance of {@link FindWarehousesFromLocationRequest }
     * 
     */
    public FindWarehousesFromLocationRequest createFindWarehousesFromLocationRequest() {
        return new FindWarehousesFromLocationRequest();
    }

    /**
     * Create an instance of {@link FindProductsFromWarehouseResponse }
     * 
     */
    public FindProductsFromWarehouseResponse createFindProductsFromWarehouseResponse() {
        return new FindProductsFromWarehouseResponse();
    }

    /**
     * Create an instance of {@link Product }
     * 
     */
    public Product createProduct() {
        return new Product();
    }

    /**
     * Create an instance of {@link FindWarehouseByIdRequest }
     * 
     */
    public FindWarehouseByIdRequest createFindWarehouseByIdRequest() {
        return new FindWarehouseByIdRequest();
    }

    /**
     * Create an instance of {@link RemoveWarehousesFromLocationRequest }
     * 
     */
    public RemoveWarehousesFromLocationRequest createRemoveWarehousesFromLocationRequest() {
        return new RemoveWarehousesFromLocationRequest();
    }

    /**
     * Create an instance of {@link FindAllProductsResponse }
     * 
     */
    public FindAllProductsResponse createFindAllProductsResponse() {
        return new FindAllProductsResponse();
    }

    /**
     * Create an instance of {@link DeleteProductRequest }
     * 
     */
    public DeleteProductRequest createDeleteProductRequest() {
        return new DeleteProductRequest();
    }

    /**
     * Create an instance of {@link AddWarehouseToLocationRequest }
     * 
     */
    public AddWarehouseToLocationRequest createAddWarehouseToLocationRequest() {
        return new AddWarehouseToLocationRequest();
    }

    /**
     * Create an instance of {@link AddWarehouseToLocationResponse }
     * 
     */
    public AddWarehouseToLocationResponse createAddWarehouseToLocationResponse() {
        return new AddWarehouseToLocationResponse();
    }

    /**
     * Create an instance of {@link CreateProductResponse }
     * 
     */
    public CreateProductResponse createCreateProductResponse() {
        return new CreateProductResponse();
    }

    /**
     * Create an instance of {@link DeleteProductResponse }
     * 
     */
    public DeleteProductResponse createDeleteProductResponse() {
        return new DeleteProductResponse();
    }

    /**
     * Create an instance of {@link FindLocationByIdResponse }
     * 
     */
    public FindLocationByIdResponse createFindLocationByIdResponse() {
        return new FindLocationByIdResponse();
    }

    /**
     * Create an instance of {@link Location }
     * 
     */
    public Location createLocation() {
        return new Location();
    }

    /**
     * Create an instance of {@link FindAllLocationsResponse }
     * 
     */
    public FindAllLocationsResponse createFindAllLocationsResponse() {
        return new FindAllLocationsResponse();
    }

    /**
     * Create an instance of {@link FindWarehouseByIdResponse }
     * 
     */
    public FindWarehouseByIdResponse createFindWarehouseByIdResponse() {
        return new FindWarehouseByIdResponse();
    }

    /**
     * Create an instance of {@link FindLocationByNameResponse }
     * 
     */
    public FindLocationByNameResponse createFindLocationByNameResponse() {
        return new FindLocationByNameResponse();
    }

    /**
     * Create an instance of {@link DeleteWarehouseRequest }
     * 
     */
    public DeleteWarehouseRequest createDeleteWarehouseRequest() {
        return new DeleteWarehouseRequest();
    }

    /**
     * Create an instance of {@link FindWarehouseByNameResponse }
     * 
     */
    public FindWarehouseByNameResponse createFindWarehouseByNameResponse() {
        return new FindWarehouseByNameResponse();
    }

    /**
     * Create an instance of {@link FindProductByIdResponse }
     * 
     */
    public FindProductByIdResponse createFindProductByIdResponse() {
        return new FindProductByIdResponse();
    }

    /**
     * Create an instance of {@link FindAllWarehousesResponse }
     * 
     */
    public FindAllWarehousesResponse createFindAllWarehousesResponse() {
        return new FindAllWarehousesResponse();
    }

    /**
     * Create an instance of {@link CreateWarehouseResponse }
     * 
     */
    public CreateWarehouseResponse createCreateWarehouseResponse() {
        return new CreateWarehouseResponse();
    }

    /**
     * Create an instance of {@link Producer }
     * 
     */
    public Producer createProducer() {
        return new Producer();
    }

}
