//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.29 at 09:11:55 PM EEST 
//


package com.training.quizzer.soap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for product complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="product">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="productId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="productName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="productProducerId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="productWarehouse" type="{http://training.com/quizzer/soap}warehouse"/>
 *         &lt;element name="productQuantity" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "product", propOrder = {
    "productId",
    "productName",
    "productProducerId",
    "productWarehouse",
    "productQuantity"
})
public class Product {

    protected long productId;
    @XmlElement(required = true)
    protected String productName;
    protected long productProducerId;
    @XmlElement(required = true)
    protected Warehouse productWarehouse;
    protected long productQuantity;

    /**
     * Gets the value of the productId property.
     * 
     */
    public long getProductId() {
        return productId;
    }

    /**
     * Sets the value of the productId property.
     * 
     */
    public void setProductId(long value) {
        this.productId = value;
    }

    /**
     * Gets the value of the productName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductName() {
        return productName;
    }

    /**
     * Sets the value of the productName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductName(String value) {
        this.productName = value;
    }

    /**
     * Gets the value of the productProducerId property.
     * 
     */
    public long getProductProducerId() {
        return productProducerId;
    }

    /**
     * Sets the value of the productProducerId property.
     * 
     */
    public void setProductProducerId(long value) {
        this.productProducerId = value;
    }

    /**
     * Gets the value of the productWarehouse property.
     * 
     * @return
     *     possible object is
     *     {@link Warehouse }
     *     
     */
    public Warehouse getProductWarehouse() {
        return productWarehouse;
    }

    /**
     * Sets the value of the productWarehouse property.
     * 
     * @param value
     *     allowed object is
     *     {@link Warehouse }
     *     
     */
    public void setProductWarehouse(Warehouse value) {
        this.productWarehouse = value;
    }

    /**
     * Gets the value of the productQuantity property.
     * 
     */
    public long getProductQuantity() {
        return productQuantity;
    }

    /**
     * Sets the value of the productQuantity property.
     * 
     */
    public void setProductQuantity(long value) {
        this.productQuantity = value;
    }

}
